module.exports = {
  User: require('./User'),
  Course: require('./Course'),
  Enrollment: require('./Enrollment'),
  LearningMaterial: require('./LearningMaterial'),
  Assignment: require('./Assignment'),
  Submission: require('./Submission'),
  Feedback: require('./Feedback'),
  Quiz: require('./Quiz'),
  Result: require('./Result'),
  Announcement: require('./Announcement'),
  Discussion: require('./Discussion'),
  Message: require('./Message'),
  Notification: require('./Notification'),
  Attendance: require('./Attendance'),
  Progress: require('./Progress'),
  Certificate: require('./Certificate'),
  Review: require('./Review'),
  CalendarEvent: require('./CalendarEvent'),
  Activity: require('./Activity'),
  Payment: require('./Payment'),
};
